name: main

on:
  push:
    tags: ['*']

jobs:
  build:
    name: Build wheels on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.9 - 3.13"
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1
        with:
          output-dir: dist
        env:
          CIBW_BUILD: cp39-*
          CIBW_ARCHS_LINUX: native
          CIBW_ARCHS_WINDOWS: native
          CIBW_ARCHS_MACOS: x86_64 arm64
      - name: Upload wheelhouse artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.whl
          name: wheels-${{matrix.os}}
          retention-days: 1

  upload:
    name: Upload wheels to PyPI
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download wheelhouse artifact
        uses: actions/download-artifact@v5
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1.13
        with:
          password: ${{secrets.PYPI_TOKEN}}
